spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:/Users/szymo/uploads/
  jpa:
    hibernate:
      ddl-auto: none
app:
  storage:
    location: /Users/szymo/uploads/